### ISSUE TITLE
Introduce a relative Base URL variable

### ISSUE THREAD

**Issue by RobLoach** [kalamuna/kalastatic#134]
Use that for the base for all links.

This allows hosting KalaStatic at a URL that doesn't live at `/`...

Example: https://kalamuna.github.io/kalastatic

**Comment by madeofpeople** [comment]
Relative files option on metalsmith-permalink is something we may want to look into, and make sure is working 
https://github.com/segmentio/metalsmith-permalinks#relative-files

**Comment by RobLoach** [comment]
Relative duplicates files across all directories, resulting in the browser loading files multiple times when browsing.

Perhaps metadata setting, or "url" in package.json with your packagejson plugin? Then prefix them in all local URLs in the templates.

**Comment by madeofpeople** [comment]
root_url?

**Comment by madeofpeople** [comment]
lets be careful not to name things in package.json like "url" or something, maybe even namespace it.

**Comment by madeofpeople** [comment]
PR #195  looks to resolve this.... 

@RobLoach 
Is there such a thing as multiple env variables?
I ask because the "production vs dev" duality isnt really fit here, we use that for uglification and such the question for base URL is "is it drupal or not"

Can we cover both cases with setting an env variable?
How do we handle this on deploy? In the instance of running a drupal instance in kbox2?

**Comment by RobLoach** [comment]
> Is there such a thing as multiple env variables?

Yup, can set multiple variables....

```
export NODE_ENV=production
export SOMETHINGELSE=somethingelse
```

I'll move this to the wiki.

**Comment by madeofpeople** [comment]
Wiki page to be updated.
