### ISSUE TITLE
reduce build times

### ISSUE THREAD

**Issue by thiagodemellobueno** [kalamuna/kalastatic#187]
we're pushing 35 seconds per build.

we should see where our bottlenecks are and simplify where possible.

I think styeguide generation, and the metalsmith build are the two largest chunks.

But rebuilding those two things is important for any kind of live reload scenario.

Just creating the issue so we're tracking this, and at the very least stay on top of any additional expansion.

**Comment by madeofpeople** [comment]
we could have different metalsmith jsons for different tasks.

we should only rebuild metalsmith when necessary.

styleguide should only be rebuilt when changes in components happen.

this is generally fine for building to deploy, but it makes development cludgy.

**Comment by RobLoach** [comment]
Some random ideas...

- Improve and move to metalsmith-kss
- Switch to kalastatic-cli
  - It caches compiled templates, so it doesn't re-compile for each source
  - Use `layout:` rather than `extends`? Might cache templates nicer?
- Upgrade to [iojs](https://iojs.org), [`node --harmony`](https://github.com/joyent/node/wiki/es6-(a.k.a.-harmony)-features-implemented-in-v8-and-available-in-node), Metalsmith 2.x
- Switch to [`metalsmith-watch`](https://github.com/FWeinb/metalsmith-watch) and clean it up a bit

**Comment by madeofpeople** [comment]
I'm curious about iojs, it does seem that it IS in fact gaining traction. 
What are your thoughts?

metalsmith-watch sounds legit.

unsure what you mean by layout rather than extends... you mean rather than templates?
from what I can tell there are no real benefits (and a few bugs) https://github.com/superwolff/metalsmith-in-place/issues/15

**Comment by madeofpeople** [comment]
How are you handling cache devalidation in metalsmith-cli?

**Comment by madeofpeople** [comment]
I've had faster build times lately, closer to 13 secs... but we do want to keep an eye on this.

**Comment by madeofpeople** [comment]
Is a "metalsmith-changed"
https://www.npmjs.com/package/metalsmith-changed

**Comment by RobLoach** [comment]
@thiagodemellobueno Build times have improved with KSTAT? Can we close this?
