### ISSUE TITLE
Demonstrate components in Kalastatic templates rendering in a Drupal context

### ISSUE THREAD

**Issue by RobLoach** [kalamuna/kalastatic#217]
Let's focus on some patterns in Panopoly/Drupal since we know that markup will be there with the demo content and base install:
- [x] .teasers
- [x] #user-login
- [ ] .pane-panopoly-demo-list-featured-demo-items

**Comment by soniktrooth** [comment]
#user-login is done: 

http://kalastatic-kalatheme.at.kalamuna.com/user/login
http://kalastatic-kalatheme.at.kalamuna.com/sites/all/themes/kt_sub/kalastatic/build/user/

**Comment by soniktrooth** [comment]
teasers are done:

http://kalastatic-kalatheme.at.kalamuna.com/demo
http://kalastatic-kalatheme.at.kalamuna.com/sites/all/themes/kt_sub/kalastatic/build/examples/news/

**Comment by andrewmallis** [comment]
https://www.drupal.org/project/componentize
and 
https://www.drupal.org/project/zen

have some drupal component thinking we should consider before re-inventing the wheel. I am not sure that componentizing Drupal is within the scope of kalastatic just just yet.

**Comment by madeofpeople** [comment]
so this wasnt so much about componentizing drupal, as much as demonstrating html prototyping in kalastatic, with relevant examples (in many cases drupal comes out the other end).

**Comment by soniktrooth** [comment]
I think this is more about having a handful of common Drupal components to demonstrate how the 'prototyping -> Drupal' workflow can work. These can serve as examples that can be shown in presentations and for devs to copy when using KS in the wild. Having said that, we might as well pick these components from someone else's exhaustive list rather than come up with our own.

**Comment by soniktrooth** [comment]
So I find componentize interesting from the point of view that it seems to be implementing a second theme layer over the top of what's in core. 

Makes me wonder:
 - how performant it is
 - how easy it would be to steal/reuse what they've done to make it use Swig (or whatever templating system we choose to move to) instead. 

This would a huge leap in integrating Drupal and KS because then the KS templates would be canonical rather than having to do the little dance where you copy the markup from the Drupal side, make a template out of it and then hope it original markup doesn't change at some point in the future.

**Comment by andrewmallis** [comment]
this was more of a 1.x approach
