### ISSUE TITLE
Provide nicer urls for Kalastatic within drupal

### ISSUE THREAD

**Issue by soniktrooth** [kalamuna/kalastatic#234]
Current solution provides a menu callback at kalastatic/prototype but just does a drupal_goto() and redirects to index.html inside the build folder which gives us ugly urls. e.g. `http://kalatheme.local/sites/all/themes/kt_sub/kalastatic/build/examples/`

I've toyed with the idea of implementing a `hook_preprocess_html` that puts the index.html contents into a variable and then provide a html.tpl that prints only that variable. This works for the front page but as soon as you navigate anywhere else then we're back to the ugly urls. 

Thoughts on sort of .htaccess based approach? We could just make kalastatic/prototype redirect to `sites/all/themes/kt_sub/kalastatic/build` and hopefully the work we did to make all the urls relative within KS would mean it all holds together?

Work to take place in
https://github.com/kalamuna/kalastatic_dot_module

**Comment by soniktrooth** [comment]
This same issue applies to the styleguide.

**Comment by madeofpeople** [comment]
So pantheon and .htaccess are not friends.

**Comment by soniktrooth** [comment]
My epiphany over on #243 about delivery callbacks may provide us with a leg up to making this happen.

**Comment by soniktrooth** [comment]
It took some backflips with headers and mime types but it's working. 
Check out: http://kalastatic-kalatheme.at.kalamuna.com/kalastatic/prototype

Style guide is still an issue though because it doesn't use <base> like the prototype. We have a couple of options: 
1. Use <base> in the styleguide - @RobLoach or @madeofpeople would need to confirm is this is a possibility
2. Alternatively, the module could detect when a styleguide url is being visited and append the extra path needed.

**Comment by soniktrooth** [comment]
@RobLoach or @madeofpeople can you let me know if option 1 is a possibility and I will assign it to one of you, otherwise I will add some more conditional logic in the module

**Comment by soniktrooth** [comment]
#237 should address this

**Comment by soniktrooth** [comment]
Nice urls are up and working. Check out 
- http://kalastatic-kalatheme.at.kalamuna.com/kalastatic/prototype
- http://kalastatic-kalatheme.at.kalamuna.com/kalastatic/prototype/styleguide/

A few other things to consider:
- do we want to refine this further and have them live at `/prototype` and `/styleguide`? There maybe a few logic implications here because the styleguide lives inside the build folder along with the rest of the prototype even though it's discreetly different. The current method is basically just pointing `/kalastatic/prototype` to the build folder and then the structure from that point down remains intact. It could be possible to implement some logic specifically for the style guide though.
- the Home button on the prototype does nothing. We should wire it back up but where should it point? To prototype home or to Drupal home or back to the Kalastatic config page where the prototype link is? 
- Same goes for the styleguide—the home link actually links back to Drupal home but should possibly be different.

**Comment by RobLoach** [comment]
Seeing the base URL as kalatheme.local:

Failed to load resource: net::ERR_NAME_NOT_RESOLVED
http://kalatheme.local/profiles/panopoly/modules/panopoly/panopoly_theme/css/panopoly-layouts.css?nxs5d8 Failed to load resource: net::ERR_NAME_NOT_RESOLVED 

Just needs a re-build with http://kalastatic-kalatheme.at.kalamuna.com I suppose.

**Comment by andrewmallis** [comment]
/kalastatic/* sounds good for now, and provides a reserved namespace. It won't collide and we can more easily permission things (if needed).
Also helps build the name up.

**Comment by andrewmallis** [comment]
The little house home link we have here is really quite particular to the kalastatic "website" that the prototype demos. Other prototypes we build will at the end of the day be unique and all this will get blown away.

However, when kalastatic is first installed, the home link exists. In that context, a link back to Drupal site at ``/`` will help the user exit the prototype space more clearly. 


When on the styleguide, 
``/kalastatic/prototype/styleguide/*``
the user will want to get back to the prototype landing page, and the website homepage. We don't make that very clear currently.

My suggestion is as follows:

![header](https://cloud.githubusercontent.com/assets/249362/11286849/407b6ba0-8ecc-11e5-86f3-49695b5bf85c.jpg)

where the house links back to ``/`` – in Drupal that would be the site, and stand-alone the prototype home.

The text link "Home" should instead say "Prototype" and link to ``/kalastatic/prototype/`` in the Drupal context. In a stand alone context, it should probably not exist at all (since the house gets us the prototype home). This last paragraph likely poses implementation challenges in the blueprint model, but I am just thinking through the UX.

**Comment by andrewmallis** [comment]
I haven't looked at the magic getting us these URLs @soniktrooth but I am sure it is mesmerizing. Great job!

**Comment by soniktrooth** [comment]
@RobLoach If you could check out https://github.com/kalamuna/kalastatic_dot_module/blob/master/kalastatic.module#L181-L244

There are two functions doing the magic, the page callback and the delivery callback. The delivery callback was largely copied from `drupal_deliver_ajax()` with all the stuff removed that was returning it as JSON removed. I'm unsure if there's not escaping (or other things) going on then it might be a security risk. 

The crux of the page callback is just finding the right file within kalastatic and returning file_get_contents($file). This works as is for html files but needed some extra massaging for css, js and images so that we're setting the appropriate headers. Again—I'm a little unsure of security implications here—I'm not used to dealing with this sort of low level stuff and generally assume that many smarter people than I have  taken care of it :dancers:

**Comment by RobLoach** [comment]
> I'm a little unsure of security implications here

Since either `'js'` or `'css'` are expected in [the menu callback](https://github.com/kalamuna/kalastatic_dot_module/blob/master/kalastatic.module#L138), the user input is sanitized. [Bobby tables](http://bobby-tables.com/) won't be hitting us any time soon. Looks pretty good, and helps with easing integration, is there anything on the KalaStatic side that we'd need to do?
