### ISSUE TITLE
automate resource sharing from Drupal to the prototype

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#243]
[kalastatic_dot_module](https://github.com/kalamuna/kalastatic_dot_module) provides CSS and JS that is pasted into the prototype manually. We are seeking to automate this process as part of the build.

**Comment by soniktrooth** [comment]
@madeofpeople see https://github.com/kalamuna/kalastatic_dot_module/blob/master/kalastatic.module#L51-L67

There is a menu callback for both the css and js. Just hit `kalastatic/drupal-css` or `kalastatic/drupal-js` and you'll get a Drupal ajax command array. You can ignore most of it but there should be an insert command object whose data property contains the markup for the css/js (depending on which url you hit). It's encoded so all the pointy brackets come through as `\u003C` etc. Hopefully it won't be too much of an issue to unencode on your end because I don't think there's much I can do about it on my end. 

Let me know if there are any issues

**Comment by soniktrooth** [comment]
Ok, so I just had an epiphany and realised we can provide our own delivery callback to the menu items. This should fix up the encoding issues.

**Comment by madeofpeople** [comment]
:100:

**Comment by soniktrooth** [comment]
Ok, here it is: https://github.com/kalamuna/kalastatic_dot_module/commit/3d39f85802100b5cf6e486300c9ba9ab5abd2d20

I made the delivery callback by stealing bits from [ajax_deliver](https://api.drupal.org/api/drupal/includes!ajax.inc/function/ajax_deliver/7)

It works great and should work for what you need @madeofpeople but I wouldn't mind @RobLoach's eyes over it to check that I'm not making some sort of security faux pas here.

**Comment by soniktrooth** [comment]
See my comment here regarding security implications: https://github.com/kalamuna/kalastatic/issues/234#issuecomment-159720622

**Comment by RobLoach** [comment]
Assessment is here: https://github.com/kalamuna/kalastatic/issues/234#issuecomment-160851336
