### ISSUE TITLE
Ingest components for a 'longterm' "component library" from EECS / Progenity

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#31]
There are architectural components / design patterns we should consider and drop into the styleguide as a start state for every site.

This issue seeks to identify some components and vernacular that combine to for the site IA. 
- CTA
- Hero
- Lede

We also tend to have these container type things which contain copy and or images and or columns…

Bootstrap provides us with some component patterns also.
How do we want to approach this question?
### ref:
- https://github.com/davidhund/styleguide-generators
- https://gimmebar.com/collection/4ecd439c2f0aaad734000022/front-end-styleguides-and-pattern-libraries

**Comment by madeofpeople** [comment]
Here's some work we did for UCSF that I think can inform this conversation a bit.

https://drive.google.com/open?id=0B6sweyW2_IqFR1NMSmVLbGVNeFE&authuser=0

**Comment by madeofpeople** [comment]
*Hero

*Lede

* CTA
** Title
** SubTitle
** Link

* Different Mobile Grids
** 4-6-12
** 3-6-12
** 3-3-6
** 3-6-6
** 4-6-6
** 3-4-12
** 3-4-6
** 3-4-4

*Touts
** Image (opt)
** TItle
** Blurb
** Link

* List Tout
** Header
** Image (opt)
** Blurb (opt)
** Title
** List (configurable to different lengths)
*** Label
*** Link

* WYSIWYG Section
** Title
** Lorem (configurable to different lengths ) 

* Person (hcard)
** Image
** Name
** Blurb (opt)
** Subfields (optional or other component?)
*** Title
*** Company
*** Email
*** Social

**Comment by madeofpeople** [comment]
There's a set of possibly useful components here
https://github.com/kalamuna/casperguide

specifically in /components/… 

Someone want to review?

**Comment by madeofpeople** [comment]
Some of this overlaps with the discussion at #202

**Comment by madeofpeople** [comment]
I think for forward momentum in success this ticket needs to be broken up in to granular winnables.

**Comment by soniktrooth** [comment]
@andrewmallis mentioned in Hangout and on Slack that there were a good list of Drupal components in Zen. Can we get link to that in here?

**Comment by madeofpeople** [comment]
Changed the name to generalize the issue.

A lot of work has been done in the component space in those sites.

So far this issue is one of those open ended "do all the things" ... 

So rescoping in the sense of "let's ingest the bits we think are future facing, general and reusable" from existing kalastatic projects.

We can do a little work to make sure those components output usable code even when we're not passing it specific content through (if statements, and defaults)

**Comment by thiagodemellobueno** [comment]
This is no longer kalastatic-scope is it?
Now with kstat2, and cli we have something much more useful, and component libraries are external, yes/no?

**Comment by soniktrooth** [comment]
@thiagodemellobueno I think the thrust of this was more about building up a 'start state' component library that would (I assume) be part of, or work in conjunction with sass-boilerplate. So reusable things that end up on every site e.g. link component, header, nav, tout. So rather than being 'part' of KS it's something we'd want to pull in straight after we install.

**Comment by thiagodemellobueno** [comment]
so its another issue in another repo? ;)

**Comment by thiagodemellobueno** [comment]
this board…

**Comment by soniktrooth** [comment]
yeah, maybe it belongs on the https://github.com/kalamuna/sass-boilerplate queue.

**Comment by thiagodemellobueno** [comment]
Agreed. Let's close :)
