### ISSUE TITLE
Port KalaStatic_Dot_Module to Drupal 8

### ISSUE THREAD

**Issue by RobLoach** [kalamuna/kalastatic#361]
we're going to move the kcom blog to D8

the kalastatic will combine with the module and we will need to move this along into a beta state on d.o. so that we can leverage the composer workflow

https://www.drupal.org/project/kalastatic

**Comment by andrewmallis** [comment]
@RobLoach mentions

> KalaStatic_Dot_Module could be the Prototype/Styleguide itself. The application of KalaStatic, rather then just referencing stuff from KalaStatic.

but I don't see how this helps us meet our design goals and [user stories](https://docs.google.com/spreadsheets/d/1P0k9oiO5XFktye-0rr7YIuvi8IU1NeqvG1F1Ci-Gk6A/edit#gid=0)

I would like to include common drupal+kalatheme stylesheets and javascript in my prototypes so that I can ensure the stylesheets I generate are useful beyond the lifespan of the prototype.

I want to see if the css and js introduced by the module I just installed break the styleguide, or functionality of existing components

I want kalatheme to be able to reliably access resources located in the kalastatic directory

I want Drupal to serve the Kalastatic directory in a convenient route (menu?) so that I can use my usual workflows to view its output.

**Comment by RobLoach** [comment]
kalastatic_dot_module provides some helpers to Drupal to make it work nicely with kalastatic. Still has a use case.

It's being used on KBLOG. Going to leave this issue open until we have a stable release of it.

**Comment by RobLoach** [comment]
We hae the module. Going to close this, and open individual issues/PRs for follow ups.
