### ISSUE TITLE
Documentation: Version Strategy

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#403]
building on https://github.com/kalamuna/kalastatic/issues/74

We recently jumped to 3.0.1.
There is talk about a 4.0.0 alreadyin #397.

I understand we want to represent breaking changes, but more important than that with version numbers we should be introducing some new functionality.

If we are pushing out so many breaking changes, then we don't have a stable product and should consider naming conventions like so:

2.0.0-beta.12

**Comment by RobLoach** [comment]
The need for [moving to `3`](https://github.com/kalamuna/kalastatic/blob/master/CHANGELOG.md#changelog) was because KSS-beta.17 introduced some breaking changes that we needed for Twig to work correctly. The need for [semantic versioning](http://semver.org) is shown in this use case....

1. Project uses KalaStatic (HSA for example) `npm i kalastatic --save`
2. We release a new `beta.12` with a new KSS
3. HSA runs `npm install`, which automatically brings in the latest `beta.12`
4. HSA then breaks because they get the latest KSS

Semantic versioning, and moving up a major release, ensures that when they run `npm install`, it doesn't automatically bring in the latest version. They'd stick on version 2, while we can keep on moving with version 3. In order for them to upgrade, they'd have to...

1. Run [`ncu`](https://www.npmjs.com/package/npm-check-updates) or see [`npm.im/kalastatic`](https://www.npmjs.com/package/kalastatic) and see there's a newer version
2. Be aware that bringing in the newer version may require some update steps
3. Update package.json manually, run `npm i && npm test`

This ensures kalastatic doesn't break every site that uses kalastatic when we make updates.
